### ISSUE TITLE
Transfer this repository to a new place for development?

### ISSUE THREAD

**Issue by Neustradamus** [xmpphp/xmpphp#2]
Dear @Drarok, it is possible to move this repository to a new place?

The goal is to have a best code, and the main developement in the original repository.

Thanks in advance.

Regards,

Neustradamus

**Comment by Drarok** [comment]
I'm not sure where you'd want it moved to? GitHub is probably the most-used source control site on the planet currently, where would you suggest?

This in an import of the original source with a minor fix or two, applied over _10 years ago!_

A more canonical fork is available at https://github.com/cweiske/xmpphp, which as you can see is marked unmaintained. I'm pretty sure this project is dead at this point.

**Comment by Neustradamus** [comment]
@Drarok: The goal is to transfer this code and will be updated...

I have invited you in xmpphp org, can you validate it and transfert the repository into?

Thanks in advance.

**Comment by Neustradamus** [comment]
You have an email in your mailbox, please validate it.

It takes few minutes.

In the xmpphp repository -> "Settings" -> "Transfer ownership" -> "Transfer button" -> enter informations and "I understand, transfer this repository." button and you must validate that it is really you.

Thanks in advance.

**Comment by Drarok** [comment]
Why don't you just fork or clone this or the other repo? There's nothing special stored in this one.

**Comment by Neustradamus** [comment]
@Drarok: Because it is the base on GitHub, the goal is to transfer, and it will be updated...

We do not want to lost forks to merge all in mainline.

Thanks a lot in advance for this little change and to the future of XMPPHP.

PS : I have already done it into another project with success.

**Comment by Drarok** [comment]
I still don't understand why you'd prefer a transfer instead of just making a new fork, but it's done now.

**Comment by Neustradamus** [comment]
@Drarok: It is perfect, thanks! :)
